[workspace]
[package]
version = "0.1.0"
name = "primitives"
edition = "2021"

[dependencies]
eyre = "0.6.12"
ethers = "2.0.14"
serde_with = "3.8.1"
serde_json = "1.0.118"
serde = { version = "1.0.203", features = ["derive"] }
ssz_rs = { version = "0.9.0", features = ["serde"] }
hex = "0.4.3"
