[workspace]
[package]
version = "0.1.0"
name = "helios-2-script"
edition = "2021"

[[bin]]
name = "f"
path = "./bin/main.rs"

[[bin]]
name = "helios"
path = "./bin/helios.rs"

[dependencies]
dotenv = "0.15.0"
ethers = "2.0.14"
eyre = "0.6.12"
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", branch = "main" }
tokio = "1.38.0"
helios = { git = "https://github.com/xavierdmello/helios" }
primitives = { path = "../primitives" }
serde = "1.0.203"
ssz_rs = "0.9.0"
thiserror = "1.0.61"

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", branch = "main" }
