[workspace]
[package]
version = "0.1.0"
name = "helios-2-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", branch = "main" }
primitives = { path = "../../helios/primitives" }
common = { path = "../../helios/common" }